# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='booking.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rbooking.proto\"\x1f\n\rBookingUserID\x12\x0e\n\x06userid\x18\x01 \x01(\t\"B\n\x0b\x42ookingData\x12\x15\n\rBookingUserID\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0e\n\x06movies\x18\x03 \x01(\t\"\x0e\n\x0c\x45mptyBooking2\xff\x01\n\x07\x42ooking\x12\x31\n\x0eGetListBooking\x12\r.EmptyBooking\x1a\x0c.BookingData\"\x00\x30\x01\x12\x36\n\x12GetBookingByUserID\x12\x0e.BookingUserID\x1a\x0c.BookingData\"\x00\x30\x01\x12,\n\x0bPostBooking\x12\x0c.BookingData\x1a\r.EmptyBooking\"\x00\x12+\n\nPutBooking\x12\x0c.BookingData\x1a\r.EmptyBooking\"\x00\x12.\n\rDeleteBooking\x12\x0c.BookingData\x1a\r.EmptyBooking\"\x00\x62\x06proto3'
)




_BOOKINGUSERID = _descriptor.Descriptor(
  name='BookingUserID',
  full_name='BookingUserID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='BookingUserID.userid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=48,
)


_BOOKINGDATA = _descriptor.Descriptor(
  name='BookingData',
  full_name='BookingData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='BookingUserID', full_name='BookingData.BookingUserID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='BookingData.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='movies', full_name='BookingData.movies', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=116,
)


_EMPTYBOOKING = _descriptor.Descriptor(
  name='EmptyBooking',
  full_name='EmptyBooking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['BookingUserID'] = _BOOKINGUSERID
DESCRIPTOR.message_types_by_name['BookingData'] = _BOOKINGDATA
DESCRIPTOR.message_types_by_name['EmptyBooking'] = _EMPTYBOOKING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BookingUserID = _reflection.GeneratedProtocolMessageType('BookingUserID', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINGUSERID,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingUserID)
  })
_sym_db.RegisterMessage(BookingUserID)

BookingData = _reflection.GeneratedProtocolMessageType('BookingData', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINGDATA,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingData)
  })
_sym_db.RegisterMessage(BookingData)

EmptyBooking = _reflection.GeneratedProtocolMessageType('EmptyBooking', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYBOOKING,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:EmptyBooking)
  })
_sym_db.RegisterMessage(EmptyBooking)



_BOOKING = _descriptor.ServiceDescriptor(
  name='Booking',
  full_name='Booking',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=135,
  serialized_end=390,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetListBooking',
    full_name='Booking.GetListBooking',
    index=0,
    containing_service=None,
    input_type=_EMPTYBOOKING,
    output_type=_BOOKINGDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBookingByUserID',
    full_name='Booking.GetBookingByUserID',
    index=1,
    containing_service=None,
    input_type=_BOOKINGUSERID,
    output_type=_BOOKINGDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PostBooking',
    full_name='Booking.PostBooking',
    index=2,
    containing_service=None,
    input_type=_BOOKINGDATA,
    output_type=_EMPTYBOOKING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PutBooking',
    full_name='Booking.PutBooking',
    index=3,
    containing_service=None,
    input_type=_BOOKINGDATA,
    output_type=_EMPTYBOOKING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteBooking',
    full_name='Booking.DeleteBooking',
    index=4,
    containing_service=None,
    input_type=_BOOKINGDATA,
    output_type=_EMPTYBOOKING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOKING)

DESCRIPTOR.services_by_name['Booking'] = _BOOKING

# @@protoc_insertion_point(module_scope)
